// Generated by scripts/optimize-images.mjs. Do not edit by hand.
//
// Intrinsic sizes for every master in assets-src/, and the widths each one was
// encoded at. Figure reads this so a caller never hand-writes a dimension and
// the numbers cannot drift away from the files they describe.

export type ImageMeta = {
  width: number;
  height: number;
  widths: readonly number[];
};

export const IMAGES = {
  "01boot.png": { width: 692, height: 533, widths: [692] },
  "02menu.png": { width: 1261, height: 672, widths: [768, 1261] },
  "02trangcanhan.png": { width: 2560, height: 1800, widths: [768, 1536] },
  "03objectives.png": { width: 1261, height: 335, widths: [768, 1261] },
  "03scenario.png": { width: 2416, height: 1516, widths: [768, 1536] },
  "04agenda.png": { width: 864, height: 593, widths: [768, 864] },
  "05hoso.png": { width: 2560, height: 4808, widths: [768, 1536] },
  "06boardflightops.png": { width: 656, height: 573, widths: [656] },
  "08pulse.png": { width: 647, height: 672, widths: [647] },
  "09touchdown.png": { width: 611, height: 296, widths: [611] },
  "10autoflight.png": { width: 1280, height: 800, widths: [768, 1280] },
  "constellationdark.png": { width: 2880, height: 1800, widths: [768, 1536] },
  "landing-page.png": { width: 1408, height: 1024, widths: [1024, 1408] },
} as const satisfies Record<string, ImageMeta>;

/** Every filename Figure will accept — a typo becomes a type error. */
export type ImageName = keyof typeof IMAGES;
